package:
  name: kubernetes-entrypoint
  description: Pod sequencing functionality for Kubernetes
  version: 0.3.1_git20241221
  epoch: 2
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/airship/kubernetes-entrypoint
      expected-commit: faed152be037ba4d7898e7df3ab4713b6a1e0d1a
      depth: -1
  - uses: go/build
    with:
      packages: .
      output: kubernetes-entrypoint
  - uses: strip
