# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: liberasurecode
  description: Erasure Code API library written in C with pluggable Erasure Code backends.
  version: 1.6.5
  epoch: 0
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - libtool
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/liberasurecode
      tag: ${{package.version}}
      expected-commit: acd8fe60f98196618218f29f5f81f909f64d458a
  - uses: autoconf/configure
    with:
      opts: |
        --disable-static \
        --disable-mmi
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: liberasurecode-dev
    description: liberasurecode dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - liberasurecode
