# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-os-ken
  description: A component-based software defined networking framework for OpenStack.
  version: 2.10.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: os-ken
  import: os_ken

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/os-ken
      tag: ${{package.version}}
      expected-commit: d0a90e5d6563a4a180c1ef7a84aa18d5ef3d23a3
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-eventlet=~0.36.1
        - py${{range.key}}-msgpack=~1.0.8
        - py${{range.key}}-ncclient=~0.6.15
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-ovs=~3.4.0
        - py${{range.key}}-packaging=~24.1
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-routes=~2.5.1
        - py${{range.key}}-webob=~1.8.8
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
