# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-pymysql
  description: Pure Python MySQL Driver
  version: 1.1.1
  epoch: 0
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pymysql
  import: pymysql

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PyMySQL/PyMySQL
      tag: v${{package.version}}
      expected-commit: 2cab9ecc641e962565c6254a5091f90c47f59b35

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: test/populated-etc-passwd
          with:
            content: |
              # import of pymysql users 'getuser' which requires either USER set in environment
              # or population of /etc/passwd.  This pipeline's modification lives in bwrap runner
              # to the next import test.  It is not necessary in docker runner.
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: test/populated-etc-passwd
      with:
        content: |
          # import of pymysql users 'getuser' which requires either USER set in environment
          # or population of /etc/passwd.  This pipeline's modification lives in bwrap runner
          # to the next import test.  It is not necessary in docker runner.
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
