# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-pyroute2
  description: Python Netlink library
  version: 0.7.12
  epoch: 0
  copyright:
    - license: GPL-2.0-or-later
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pyroute2
  import: pyroute2

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/svinota/pyroute2
      tag: ${{package.version}}
      expected-commit: 7b374fc398364dcd4d9218654d4cfb3d6305b194

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
