# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-tooz
  description: Coordination library for distributed systems.
  version: 6.3.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: tooz
  import: tooz

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/tooz
      tag: ${{package.version}}
      expected-commit: f3da28364aebb9bf4cb094cd37233452d052376c
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-fasteners=~0.19
        - py${{range.key}}-futurist=~3.0.0
        - py${{range.key}}-msgpack=~1.0.8
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-tenacity=~8.3.0
        - py${{range.key}}-voluptuous=~0.15.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
