# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-oslo-rootwrap
  description: Oslo Rootwrap
  version: 7.3.0
  epoch: 0
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: oslo.rootwrap
  import: oslo_rootwrap

var-transforms:
  - from: ${{vars.pypi-package}}
    match: '\.'
    replace: "-"
    to: mangled-package-name

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/oslo.rootwrap
      tag: ${{package.version}}
      expected-commit: 3266eccc387b53320a68695487cd2439b778acdf
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.mangled-package-name}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.mangled-package-name}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.mangled-package-name}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.mangled-package-name}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
