# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-grpcio
  description: HTTP/2-based RPC framework
  version: 1.66.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: grpcio
  import: grpc

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - build-base
      - py3-supported-build-base
      - py3-supported-cython
      - py3-supported-python-dev
  environment:
    GRPC_PYTHON_BUILD_WITH_CYTHON: 1

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc
      tag: v${{package.version}}
      expected-commit: 13cecab1c4f45902197a9f8fe4e787eb9c4d4db1
      recurse-submodules: true

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
