# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-numpy
  description: Fundamental package for array computing in Python
  version: 2.1.0
  epoch: 1
  copyright:
    - license: BSD-2-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: numpy
  import: numpy

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - build-base
      - cython
      - meson
      - py3-supported-build-base
      - py3-supported-cython
      - py3-supported-meson-python
      - py3-supported-python-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numpy/numpy
      tag: v${{package.version}}
      expected-commit: 4d929bceec7a27be9fcaa0388fc9e496d329b496
      recurse-submodules: true

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
