# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-python-dateutil
  description: Extensions to the standard Python datetime module
  version: 2.9.0.post0
  epoch: 1
  copyright:
    - license: BSD-2-Clause
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: python-dateutil
  import: dateutil

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-setuptools-scm
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dateutil/dateutil
      tag: ${{package.version}}
      expected-commit: 1ae807774053c071acc9e7d3d27778fba0a7773e

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-six=~1.16.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
