# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-manila
  description: Shared Storage for OpenStack
  version: 19.0.1
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: manila
  import: manila

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/manila
      tag: ${{package.version}}
      expected-commit: 076ce3c7a285e50330c476c9afa7104ea0e65efe
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-alembic=~1.13.2
        - py${{range.key}}-cachetools=~5.5.0
        - py${{range.key}}-defusedxml=~0.7.1
        - py${{range.key}}-eventlet=~0.36.1
        - py${{range.key}}-greenlet=~3.0.3
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-keystonemiddleware=~10.7.1
        - py${{range.key}}-lxml=~5.3.0
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-context=~5.6.0
        - py${{range.key}}-oslo-db=~16.0.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-messaging=~14.9.1
        - py${{range.key}}-oslo-middleware=~6.2.0
        - py${{range.key}}-oslo-policy=~4.4.0
        - py${{range.key}}-oslo-privsep=~3.4.0
        - py${{range.key}}-oslo-reports=~3.4.0
        - py${{range.key}}-oslo-rootwrap=~7.3.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-service=~3.5.0
        - py${{range.key}}-oslo-upgradecheck=~2.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-osprofiler=~4.2.0
        - py${{range.key}}-packaging=~24.1
        - py${{range.key}}-paramiko=~3.4.1
        - py${{range.key}}-paste=~3.10.1
        - py${{range.key}}-pastedeploy=~3.1.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-pyparsing=~3.1.2
        - py${{range.key}}-python-cinderclient=~9.6.0
        - py${{range.key}}-python-glanceclient=~4.7.0
        - py${{range.key}}-python-neutronclient=~11.3.1
        - py${{range.key}}-python-novaclient=~18.7.0
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-routes=~2.5.1
        - py${{range.key}}-sqlalchemy-utils=~0.41.2
        - py${{range.key}}-sqlalchemy=~2.0.32
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-tenacity=~8.3.0
        - py${{range.key}}-tooz=~6.3.0
        - py${{range.key}}-webob=~1.8.8
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
