# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-dogpile-cache
  description: A caching front-end based on the Dogpile lock.
  version: 1.3.3
  epoch: 2
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: dogpile.cache
  import: dogpile.cache

var-transforms:
  - from: ${{vars.pypi-package}}
    match: '\.'
    replace: "-"
    to: mangled-package-name

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlalchemy/dogpile.cache
      tag: rel_1_3_3
      expected-commit: 22db77310612ab326f8c1192e7d8e03f73abd6c4

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.mangled-package-name}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.mangled-package-name}}
      runtime:
        - py${{range.key}}-decorator=~5.1.1
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-typing-extensions=~4.12.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.mangled-package-name}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.mangled-package-name}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
