# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-osprofiler
  description: OpenStack Profiler Library
  version: 4.2.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: osprofiler
  import: osprofiler

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/osprofiler
      tag: ${{package.version}}
      expected-commit: ba8f4f47cc67216cfcb2997eb6e6c7089723b590
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-prettytable=~3.11.0
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-webob=~1.8.8
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
