# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-django-compressor
  description: ('Compresses linked and inline JavaScript or CSS into single cached files.',)
  version: 4.5.1
  epoch: 0
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: django-compressor
  import: compressor

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/django-compressor/django-compressor
      tag: ${{package.version}}
      expected-commit: 33df9384b6f047991f45a469d82a84c50021c6a5

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-django-appconf=~1.0.6
        - py${{range.key}}-django=~4.2.15
        - py${{range.key}}-rcssmin=~1.1.2
        - py${{range.key}}-rjsmin=~1.2.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
