# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-confspirator
  description: A config library for handling nested incode config groups.
  version: 0.3.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: confspirator
  import: confspirator

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/catalyst-cloud/confspirator
      tag: ${{package.version}}
      expected-commit: 60f94bb8f0fb0d08f5490b0937545a7bc683a031
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-python-slugify=~8.0.4
        - py${{range.key}}-pyyaml=~6.0.2
        - py${{range.key}}-rfc3986=~2.0.0
        - py${{range.key}}-six=~1.16.0
        - py${{range.key}}-toml=~0.10.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
