# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-pysaml2
  description: Python implementation of SAML Version 2 Standard
  version: 7.5.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pysaml2
  import: saml2

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-poetry-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/IdentityPython/pysaml2
      tag: v${{package.version}}
      expected-commit: 7508d0475e14224667bbb19e78f5fe43ac38a256

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-cryptography=~42.0.8
        - py${{range.key}}-defusedxml=~0.7.1
        - py${{range.key}}-pyopenssl=~24.2.1
        - py${{range.key}}-python-dateutil=~2.9.0.post0
        - py${{range.key}}-pytz=~2024.1
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-xmlschema=~2.5.1
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
