# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-zun
  description: OpenStack Containers service
  version: 14.0.0
  epoch: 0
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: zun
  import: zun

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/zun
      tag: ${{package.version}}
      expected-commit: 1215520711d57701876236406116228e877c7056
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-alembic=~1.13.2
        - py${{range.key}}-cotyledon=~1.7.3
        - py${{range.key}}-docker=~7.1.0
        - py${{range.key}}-eventlet=~0.36.1
        - py${{range.key}}-flask=~3.0.3
        - py${{range.key}}-futurist=~3.0.0
        - py${{range.key}}-grpcio=~1.66.0
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-keystonemiddleware=~10.7.1
        - py${{range.key}}-kuryr-lib=~3.1.0
        - py${{range.key}}-neutron-lib=~3.15.0
        - py${{range.key}}-os-brick=~6.9.0
        - py${{range.key}}-os-resource-classes=~1.1.0
        - py${{range.key}}-os-traits=~3.1.0
        - py${{range.key}}-os-vif=~3.7.0
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-context=~5.6.0
        - py${{range.key}}-oslo-db=~16.0.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-messaging=~14.9.1
        - py${{range.key}}-oslo-middleware=~6.2.0
        - py${{range.key}}-oslo-policy=~4.4.0
        - py${{range.key}}-oslo-privsep=~3.4.0
        - py${{range.key}}-oslo-rootwrap=~7.3.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-service=~3.5.0
        - py${{range.key}}-oslo-upgradecheck=~2.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-oslo-versionedobjects=~3.4.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-pecan=~1.5.1
        - py${{range.key}}-protobuf=~4.25.4
        - py${{range.key}}-psutil=~6.0.0
        - py${{range.key}}-pyroute2=~0.7.12
        - py${{range.key}}-python-cinderclient=~9.6.0
        - py${{range.key}}-python-glanceclient=~4.7.0
        - py${{range.key}}-python-neutronclient=~11.3.1
        - py${{range.key}}-pyyaml=~6.0.2
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-retrying=~1.3.4
        - py${{range.key}}-sqlalchemy=~2.0.32
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-tenacity=~8.3.0
        - py${{range.key}}-webob=~1.8.8
        - py${{range.key}}-websocket-client=~1.8.0
        - py${{range.key}}-websockify=~0.12.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
