# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-aiosqlite
  description: asyncio bridge to the standard sqlite3 module
  version: 0.17.0
  epoch: 2
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: aiosqlite
  import: aiosqlite

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-flit-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/omnilib/aiosqlite
      tag: v${{package.version}}
      expected-commit: 802b4379891083891522f0bb7a490a80b7462c88

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-typing-extensions=~4.12.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
