# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-mako
  description: A super-fast templating language that borrows the best ideas from the existing templating languages.
  version: 1.3.5
  epoch: 1
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: mako
  import: mako

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlalchemy/mako
      tag: rel_1_3_5
      expected-commit: a54313f941c5e57b009df15d778f21baf43a73d6

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-markupsafe=~2.1.5
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
