# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-zeroconf
  description: A pure python implementation of multicast DNS service discovery
  version: 0.132.2
  epoch: 0
  copyright:
    - license: LGPL-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: zeroconf
  import: zeroconf

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-cython
      - py3-supported-poetry-core
      - py3-supported-setuptools
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-zeroconf/python-zeroconf
      tag: ${{package.version}}
      expected-commit: 8dd1f99c9aeb195a74ed6b9c56b1afa891a8c28c

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-async-timeout=~4.0.3
        - py${{range.key}}-ifaddr=~0.2.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
