# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-python-neutronclient
  description: CLI and Client Library for OpenStack Networking
  version: 11.3.1
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: python-neutronclient
  import: neutronclient

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/python-neutronclient
      tag: ${{package.version}}
      expected-commit: a0ebc21ab4529ab8ef62665251285d67ee433cee
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-cliff=~4.7.0
        - py${{range.key}}-debtcollector=~3.0.0
        - py${{range.key}}-iso8601=~2.1.0
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-openstacksdk=~4.0.1
        - py${{range.key}}-os-client-config=~2.1.0
        - py${{range.key}}-osc-lib=~3.1.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-python-keystoneclient=~5.5.0
        - py${{range.key}}-requests=~2.32.3
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
