# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-magnum
  description: Container Management project for OpenStack
  version: 19.0.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: magnum
  import: magnum

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/magnum
      tag: ${{package.version}}
      expected-commit: 2d1d9d97c6a643176cbb06fc76275837ed4b3881
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-alembic=~1.13.2
        - py${{range.key}}-cliff=~4.7.0
        - py${{range.key}}-cryptography=~42.0.8
        - py${{range.key}}-decorator=~5.1.1
        - py${{range.key}}-eventlet=~0.36.1
        - py${{range.key}}-iso8601=~2.1.0
        - py${{range.key}}-jsonpatch=~1.33
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-keystonemiddleware=~10.7.1
        - py${{range.key}}-netaddr=~0.10.1
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-context=~5.6.0
        - py${{range.key}}-oslo-db=~16.0.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-messaging=~14.9.1
        - py${{range.key}}-oslo-middleware=~6.2.0
        - py${{range.key}}-oslo-policy=~4.4.0
        - py${{range.key}}-oslo-reports=~3.4.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-service=~3.5.0
        - py${{range.key}}-oslo-upgradecheck=~2.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-oslo-versionedobjects=~3.4.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-pecan=~1.5.1
        - py${{range.key}}-pycadf=~3.1.1
        - py${{range.key}}-python-barbicanclient=~7.0.0
        - py${{range.key}}-python-cinderclient=~9.6.0
        - py${{range.key}}-python-glanceclient=~4.7.0
        - py${{range.key}}-python-heatclient=~4.0.0
        - py${{range.key}}-python-keystoneclient=~5.5.0
        - py${{range.key}}-python-neutronclient=~11.3.1
        - py${{range.key}}-python-novaclient=~18.7.0
        - py${{range.key}}-python-octaviaclient=~3.8.0
        - py${{range.key}}-pyyaml=~6.0.2
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-setuptools=~75.6.0
        - py${{range.key}}-sqlalchemy=~2.0.32
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-taskflow=~5.9.1
        - py${{range.key}}-webob=~1.8.8
        - py${{range.key}}-werkzeug=~3.0.4
        - py${{range.key}}-wsme=~0.12.1
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
