# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-importlib-metadata
  description: Read metadata from Python packages
  version: 6.11.0
  epoch: 2
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: importlib-metadata
  import: importlib_metadata

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-setuptools-scm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python/importlib_metadata
      tag: v${{package.version}}
      expected-commit: 162905722eb3fab3a1ea5dd1e51ea8bf8668f762

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-zipp=~3.20.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
