# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-ncclient
  description: Python library for NETCONF clients
  version: 0.6.15
  epoch: 1
  copyright:
  dependencies:
    provider-priority: 0

vars:
  pypi-package: ncclient
  import: ncclient

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ncclient/ncclient
      tag: v${{package.version}}
      expected-commit: f0f4d95ed8613f256f0972491d6c47f53246da0b

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-lxml=~5.3.0
        - py${{range.key}}-paramiko=~3.4.1
        - py${{range.key}}-setuptools=~75.6.0
        - py${{range.key}}-six=~1.16.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
