# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-cmd2
  description: cmd2 - quickly build feature-rich and user-friendly interactive command line applications in Python
  version: 2.4.3
  epoch: 1
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: cmd2
  import: cmd2

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-setuptools-scm
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/python-cmd2/cmd2
      tag: ${{package.version}}
      expected-commit: 31d59538a740043110b08a19401fe17c940dca26

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-attrs=~24.2.0
        - py${{range.key}}-pyperclip=~1.9.0
        - py${{range.key}}-wcwidth=~0.2.13
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
