# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-anyio
  description: High level compatibility layer for multiple asynchronous event loop implementations
  version: 4.4.0
  epoch: 1
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: anyio
  import: anyio

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-setuptools
      - py3-supported-setuptools-scm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/agronholm/anyio
      tag: ${{package.version}}
      expected-commit: 053e8f0a0f7b0f4a47a012eb5c6b1d9d84344e6a

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-exceptiongroup=~1.2.2
        - py${{range.key}}-idna=~3.8
        - py${{range.key}}-sniffio=~1.3.1
        - py${{range.key}}-typing-extensions=~4.12.2
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
