# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-pytz
  description: World timezone definitions, modern and historical
  version: 2024.1
  epoch: 1
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pytz
  import: pytz

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - bash
      - build-base
      - py3-supported-build-base
      - rsync

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stub42/pytz
      tag: release_2024.1
      expected-commit: 5bea24024ee7edb2f776720c23c2be120afb7d3c

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - runs: make build/dist/test_zdump.py
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
          path: src
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
