# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-python-watcher
  description: OpenStack Watcher provides a flexible and scalable resource optimization service for multi-tenant OpenStack-based clouds.
  version: 13.0.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: python-watcher
  import: watcher

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/watcher
      tag: ${{package.version}}
      expected-commit: 413e7f08e29cb35da9e67f1a11ccb5e7f0475519
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-apscheduler=~3.10.4
        - py${{range.key}}-croniter=~2.0.7
        - py${{range.key}}-futurist=~3.0.0
        - py${{range.key}}-gnocchiclient=~7.1.0
        - py${{range.key}}-jsonpatch=~1.33
        - py${{range.key}}-jsonschema=~4.19.2
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-keystonemiddleware=~10.7.1
        - py${{range.key}}-lxml=~5.3.0
        - py${{range.key}}-microversion-parse=~2.0.0
        - py${{range.key}}-networkx=~3.3
        - py${{range.key}}-os-resource-classes=~1.1.0
        - py${{range.key}}-oslo-cache=~3.8.0
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-context=~5.6.0
        - py${{range.key}}-oslo-db=~16.0.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-messaging=~14.9.1
        - py${{range.key}}-oslo-policy=~4.4.0
        - py${{range.key}}-oslo-reports=~3.4.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-service=~3.5.0
        - py${{range.key}}-oslo-upgradecheck=~2.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-oslo-versionedobjects=~3.4.0
        - py${{range.key}}-pastedeploy=~3.1.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-pecan=~1.5.1
        - py${{range.key}}-prettytable=~3.11.0
        - py${{range.key}}-python-cinderclient=~9.6.0
        - py${{range.key}}-python-glanceclient=~4.7.0
        - py${{range.key}}-python-ironicclient=~5.8.0
        - py${{range.key}}-python-keystoneclient=~5.5.0
        - py${{range.key}}-python-monascaclient=~2.8.0
        - py${{range.key}}-python-neutronclient=~11.3.1
        - py${{range.key}}-python-novaclient=~18.7.0
        - py${{range.key}}-python-openstackclient=~7.1.3
        - py${{range.key}}-sqlalchemy=~2.0.32
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-taskflow=~5.9.1
        - py${{range.key}}-webob=~1.8.8
        - py${{range.key}}-wsme=~0.12.1
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
