# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-oslo-service
  description: oslo.service library
  version: 3.5.0
  epoch: 1
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: oslo.service
  import: oslo_service

var-transforms:
  - from: ${{vars.pypi-package}}
    match: '\.'
    replace: "-"
    to: mangled-package-name

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/oslo.service
      tag: ${{package.version}}
      expected-commit: 979ada7f673d49e0b42c70829d19187eeee379d7
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.mangled-package-name}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.mangled-package-name}}
      runtime:
        - py${{range.key}}-debtcollector=~3.0.0
        - py${{range.key}}-eventlet=~0.36.1
        - py${{range.key}}-greenlet=~3.0.3
        - py${{range.key}}-oslo-concurrency=~6.1.0
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-paste=~3.10.1
        - py${{range.key}}-pastedeploy=~3.1.0
        - py${{range.key}}-routes=~2.5.1
        - py${{range.key}}-webob=~1.8.8
        - py${{range.key}}-yappi=~1.6.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.mangled-package-name}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.mangled-package-name}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
