# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-python-cinderclient
  description: OpenStack Block Storage API Client Library
  version: 9.6.0
  epoch: 0
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: python-cinderclient
  import: cinderclient

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/python-cinderclient
      tag: ${{package.version}}
      expected-commit: f22852285dcdf2d60ae41e88915075a06818f503
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-prettytable=~3.11.0
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-stevedore=~5.3.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
