# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-octavia
  description: OpenStack Octavia Scalable Load Balancer as a Service
  version: 15.0.0
  epoch: 0
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: octavia
  import: octavia

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/octavia
      tag: ${{package.version}}
      expected-commit: e245b3af36a2bb59b3e856bdd2670aeb0f24055a
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-alembic=~1.13.2
        - py${{range.key}}-castellan=~5.1.1
        - py${{range.key}}-cotyledon=~1.7.3
        - py${{range.key}}-cryptography=~42.0.8
        - py${{range.key}}-distro=~1.9.0
        - py${{range.key}}-flask=~3.0.3
        - py${{range.key}}-futurist=~3.0.0
        - py${{range.key}}-gunicorn=~23.0.0
        - py${{range.key}}-jinja2=~3.1.4
        - py${{range.key}}-jsonschema=~4.19.2
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-keystonemiddleware=~10.7.1
        - py${{range.key}}-octavia-lib=~3.6.0
        - py${{range.key}}-openstacksdk=~4.0.1
        - py${{range.key}}-oslo-config=~9.6.0
        - py${{range.key}}-oslo-context=~5.6.0
        - py${{range.key}}-oslo-db=~16.0.0
        - py${{range.key}}-oslo-i18n=~6.4.0
        - py${{range.key}}-oslo-log=~6.1.2
        - py${{range.key}}-oslo-messaging=~14.9.1
        - py${{range.key}}-oslo-middleware=~6.2.0
        - py${{range.key}}-oslo-policy=~4.4.0
        - py${{range.key}}-oslo-reports=~3.4.0
        - py${{range.key}}-oslo-serialization=~5.5.0
        - py${{range.key}}-oslo-upgradecheck=~2.4.0
        - py${{range.key}}-oslo-utils=~7.3.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-pecan=~1.5.1
        - py${{range.key}}-psutil=~6.0.0
        - py${{range.key}}-pyasn1-modules=~0.4.0
        - py${{range.key}}-pyasn1=~0.6.0
        - py${{range.key}}-pyroute2=~0.7.12
        - py${{range.key}}-python-barbicanclient=~7.0.0
        - py${{range.key}}-python-cinderclient=~9.6.0
        - py${{range.key}}-python-dateutil=~2.9.0.post0
        - py${{range.key}}-python-glanceclient=~4.7.0
        - py${{range.key}}-python-novaclient=~18.7.0
        - py${{range.key}}-requests=~2.32.3
        - py${{range.key}}-rfc3986=~2.0.0
        - py${{range.key}}-setproctitle=~1.3.3
        - py${{range.key}}-sqlalchemy-utils=~0.41.2
        - py${{range.key}}-sqlalchemy=~2.0.32
        - py${{range.key}}-stevedore=~5.3.0
        - py${{range.key}}-taskflow=~5.9.1
        - py${{range.key}}-tenacity=~8.3.0
        - py${{range.key}}-webob=~1.8.8
        - py${{range.key}}-werkzeug=~3.0.4
        - py${{range.key}}-wsme=~0.12.1
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
