# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-openstacksdk
  description: An SDK for building applications to work with OpenStack
  version: 4.0.1
  epoch: 0
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: openstacksdk
  import: openstack

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-pbr

pipeline:
  - uses: git-checkout
    with:
      repository: https://opendev.org/openstack/openstacksdk
      tag: ${{package.version}}
      expected-commit: bd32ccd44e81174d2e3887c289e6089b77896215
  - uses: py/validate-pbr-version

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-cryptography=~42.0.8
        - py${{range.key}}-decorator=~5.1.1
        - py${{range.key}}-dogpile-cache=~1.3.3
        - py${{range.key}}-iso8601=~2.1.0
        - py${{range.key}}-jmespath=~1.0.1
        - py${{range.key}}-jsonpatch=~1.33
        - py${{range.key}}-keystoneauth1=~5.8.0
        - py${{range.key}}-netifaces=~0.11.0
        - py${{range.key}}-os-service-types=~1.7.0
        - py${{range.key}}-pbr=~6.1.0
        - py${{range.key}}-platformdirs=~4.2.2
        - py${{range.key}}-pyyaml=~6.0.2
        - py${{range.key}}-requestsexceptions=~1.4.0
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
