# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-repoze-lru
  description: A tiny LRU cache implementation and decorator
  version: 0.7
  epoch: 0
  copyright:
  dependencies:
    provider-priority: 0

vars:
  pypi-package: repoze.lru
  import: repoze.lru

var-transforms:
  - from: ${{vars.pypi-package}}
    match: '\.'
    replace: "-"
    to: mangled-package-name

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/repoze/repoze.lru
      tag: ${{package.version}}
      expected-commit: 66ce33da9114e9219dcb47d6d7412cd2dcedcd5f

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.mangled-package-name}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.mangled-package-name}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.mangled-package-name}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.mangled-package-name}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
