# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-pysnmp-lextudio
  description: 
  version: 5.0.33
  epoch: 0
  copyright:
    - license: BSD-2-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pysnmp-lextudio
  import: pysnmp

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-poetry-core

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lextudio/pysnmp
      tag: v${{package.version}}
      expected-commit: 41a1a97a3e75f9a4687aa02cdc64e6e9ecc2fcf9

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-pyasn1=~0.6.0
        - py${{range.key}}-pysmi-lextudio=~1.4.3
        - py${{range.key}}-pysnmpcrypto=~0.0.4
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
