# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-scrypt
  description: Bindings for the scrypt key derivation function library
  version: 0.8.24
  epoch: 1
  copyright:
    - license: BSD-2-Clause
  dependencies:
    provider-priority: 0

vars:
  pypi-package: scrypt
  import: scrypt

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - build-base
      - openssl-dev
      - py3-supported-build-base
      - py3-supported-python-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/holgern/py-scrypt
      tag: v${{package.version}}
      expected-commit: da2882ff2a1d4cfa0ff06ccc933942939bf65b6c

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
