# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-only

package:
  name: py3-eventlet
  description: Highly concurrent networking library
  version: 0.36.1
  epoch: 0
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: eventlet
  import: eventlet

data:
  - name: py-versions
    items:
      3.10: '310'

environment:
  contents:
    packages:
      - py3-supported-build-base
      - py3-supported-hatch-vcs
      - py3-supported-hatchling

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eventlet/eventlet
      tag: ${{package.version}}
      expected-commit: 43edc1fe0fb2559b8285f150f52a0c1f1b0a8881

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
      runtime:
        - py${{range.key}}-dnspython=~2.6.1
        - py${{range.key}}-greenlet=~3.0.3
    pipeline:
      - uses: py/build-wheel
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            imports: |
              import ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import ${{vars.import}}
